### ISSUE TITLE
اضافه شدن صفحه هوش تجاري

### ISSUE THREAD

**Issue by HaShamaei** [ViraAfzaran/ViraSite#1]
![0dfeb264736e8c5c2c031ec23edb509003c8cc5b02c45d3d57 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17108130/13378041/33ec131a-de0b-11e5-979a-29258bd1e800.jpg)
![9a1880a973e1a52c0667a27b30daa5bffe5ab3fc8cbcbef12d pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17108130/13378042/33f21292-de0b-11e5-8c72-acc873c19423.jpg)
![b78f6aa468f08b5f3779cd65b0609bf6f793d4955ebe5e26b7 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17108130/13378043/33f758b0-de0b-11e5-86bd-558288b087be.jpg)
![f14bd690d9fc624a6e69b9e0da8ed659d5dd2b3466c62a8637 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17108130/13378044/33fc5e50-de0b-11e5-8f46-c7eca6473fcb.jpg)

**Comment by HaShamaei** [comment]
چرا سازمان به سیستمهای هوش تجاری نیاز دارد؟
دنیای رقابتی امروز دنیایی پویا با شیب تغییرات بسیار بالاست . شرایط اقتصادی ، سیاسی ، تکنولوژی و اجتماعی با چنان سرعتی تغییر می کنند که اگر سازمان نتواند این تغییرات را پیش بینی نموده و سریعا خود را بر اساس آن  به روز نماید ، دیر یا زود از گردونه رقابت و بازار خارج می شود . با سیستمهای هوش تجاری می توان در کنار تحلیل شاخصهای درون سازمانی ، محرکهای برون سازمانی را نیز پیش بینی و تحلیل نمود .

قابلیتها و امکانات : 
قابلیت  انجام تحلیل های آماری با روشهای آنالیز همبستگی ، آنالیز واریانس ، رگرسیون و ...
استفاده از تکنیک های داده کاوی جهت کشف حقایق پنهان در داده ها
جهت تحلیلهای چند متغیره و چند بعدیOLAP امکان استفاده از تکنولوژی
پاکسازی داده ها با استفاده از ابزار ETL

فواید استفاده از سیستم :
تحلیل همزمان اطلاعات درون سازمانی و برون سازمانی
افزایش قدرت تصمیم گیری مدیران
پیش بینی چالشها و فرصتهای سازمان و بهره گیری از آنها
افزایش سود آوری و سبقت از رقبا
یکپارچه سازی سیستمهای جزیره ایی 

راهی موثر برای ایجاد یک سیستم جامع

**Comment by ghost** [comment]
اضافه شد
http://viraafzaran.ir/%d9%87%d9%88%d8%b4-%d8%aa%d8%ac%d8%a7%d8%b1%db%8c/
